#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Mon Sep 22 19:43:38 CST 2025
create=true
farmersdelight=true
regions_unexplored=true
